name: resq_link
description: A new Flutter project for ResQ Link.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '^3.8.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  flutter_animate: ^4.1.1+1
  image_picker: ^1.0.7
  http: ^1.2.1
  supabase_flutter: ^2.3.3
  flutter_client_sse: ^2.0.1
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  geolocator: ^11.0.0
  geocoding: ^2.1.1
  vibration: ^3.1.3
  torch_light: ^1.1.0
  just_audio: ^0.9.36
  flutter_local_notifications: ^17.1.2
  permission_handler: ^11.3.1
  flutter_tts: ^3.8.5
  url_launcher: ^6.2.5
  flutter_dotenv: ^5.1.0
  flutter_webrtc: ^0.14.2
  http_parser: ^4.1.2
  udp: ^5.0.3
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/warning.mp3
    - .env